### ISSUE TITLE
missing msp430.h

### ISSUE THREAD

**Issue by chrigu1981** [abhra0897/msp430_cc1101_energia_v2#1]
```
libraries/MSP430-CC1101-Energia-Library/cc1101.h:5:10: fatal error: msp430.h: No such file or directory #include <msp430.h>
```

**Comment by abhra0897** [comment]
@chrigu1981 This driver library doesn't have any
msp430.h file. So, you're using my older library it seems. Please delete that library and download this one (v2). 
If the error persists, let me know.

**Comment by chrigu1981** [comment]
same on v2

**Comment by abhra0897** [comment]
I think you are doing something wrong. Delete both the previous version and v2. Download only the v2 and place the library in the libraries folder of energia. Restart energia.
Go to examples, select this library, and select an example (from 3 examples). Compile it.

If it still doesn't work, please upload a screenshot of the libraries folder.
