### ISSUE TITLE
sir i need help

### ISSUE THREAD

**Issue by waleedsworld** [abhra0897/msp430_cc1101_energia_v2#4]
kind sir i have the same cc1101 with 8 pin i need help please i am a student researching on 315mhz devices i want to mimic my key fob using cc1101 i need immediate help in this project
could you help me i am not in a financial stability so i cant pay you for assistance but ill be grateful for your help

**Comment by abhra0897** [comment]
Sorry to say that I've no idea how to mimic car keyfobs using CC1101. You may try to capture the raw signal using an RTL-SDR and then use the library to replicate that signal with CC1101. But that's all I can tell.

**Comment by waleedsworld** [comment]
Sir could you once just connect the wires with cc1101 8pin with arduino run
the space teddy please

**Comment by abhra0897** [comment]
Did you even check SpaceTeddy's library? The connection is given at the very beginning of the Readme. Anyway, here it is for you:

CC1101<->Arduino

Vdd    -    3.3V
SI     -    MOSI (11)
SO     -    MISO (12)
CS     -    SS   (10)
SCLK   -    SCK  (13)
GDO2   -    GPIO ( 3)
GDO0   -    Unused
GND    -    GND
